/** Display-only Traditional Chinese copy. Protocol/domain values are never changed. */
const copy: Readonly<Record<string, string>> = {
  "SIMULATED": "模擬",
  "SIMULATED SCENARIO": "模擬情境",
  "SIMULATED EXAMPLES": "模擬示例",
  "SIMULATED ROUTE": "模擬路線",
  "SIMULATED ROUTE VALUES": "模擬導航數據",
  "SIMULATED JOURNEY CONTEXT": "模擬旅程資訊",
  "Journey": "行程",
  "Journey update available": "行程更新待確認",
  "Journey updated": "行程已更新",
  "Munich": "慕尼黑",
  "MUNICH": "慕尼黑",
  "Stuttgart": "斯圖加特",
  "STUTTGART": "斯圖加特",
  "Origin · departed": "起點 · 已出發",
  "Dinner": "晚餐",
  "Reservation": "預約",
  "Hotel Ambra · 12 min stop": "Ambra 飯店 · 停留 12 分鐘",
  "A–8 Autobahn": "A–8 高速公路",
  "Traffic delay · +8 min": "交通延誤 · +8 分鐘",
  "Shared": "提案",
  "Added": "已加入",
  "Confirmed by HMI Gateway": "經 HMI 閘道確認",
  "Destination · 98 km": "目的地 · 98 公里",
  "to destination": "至目的地",
  "min": "分鐘",
  "Next stop": "下一站",
  "Currently": "目前路段",
  "on A–8": "A–8 高速公路",
  "ETA 19:44 · DEMO": "預計 19:44 · 模擬",
  "ETA 19:32": "預計 19:32",
  "Ask for a whole-journey recommendation": "詢問旅程建議",
  "Ask about this journey… e.g. a quick dinner stop": "詢問行程，例如：沿途用餐地點",
  "Recommend": "建議",
  "Paused while driver attention is needed.": "駕駛忙碌，暫緩非必要資訊。",
  "Waiting for a current driver-load state before showing journey suggestions.": "等待駕駛負荷資訊後再提供建議。",
  "Checking current journey evidence…": "正在核對旅程資訊…",
  "Passenger proposal · shared gateway state": "乘員提案 · 共享行程",
  "KEEP ROUTE": "維持路線",
  "ACCEPT": "接受",
  "Decline": "拒絕",
  "Approve": "同意",
  "Navigate": "導航",
  "Route options": "路線選項",
  "Radio": "廣播",
  "Climate": "空調",
  "22°C Auto": "22°C 自動",
  "Phone": "電話",
  "Connected": "已連線",
  "DINING": "美食",
  "GUIDE": "指南",
  "LOCAL FLAVOR": "在地風味",
  "Explore places along your journey.": "探索沿途餐廳。",
  "CURATED SPOTS": "精選餐廳",
  "Compare cuisine and simulated journey impact.": "比較料理與模擬繞路時間。",
  "FILTER &amp; SEARCH": "篩選與搜尋",
  "All": "全部",
  "Fine dining": "精緻餐飲",
  "Cafés": "咖啡館",
  "Vegan": "植物料理",
  "AURA · IDLE EXAMPLE PLACES": "AURA · 待命 · 示例餐廳",
  "Mediterranean · ★ 4.8 · 繞路 +5 min": "地中海料理 · ★ 4.8 · 繞路 +5 分鐘",
  "Modern · ★ 4.9 · +4 min": "現代料理 · ★ 4.9 · +4 分鐘",
  "Café · ★ 4.7 · +3 min": "咖啡館 · ★ 4.7 · +3 分鐘",
  "Vegan · ★ 4.6 · +6 min": "植物料理 · ★ 4.6 · +6 分鐘",
  "MEDIA PLAYER": "影音播放",
  "MUSIC &amp; AUDIO": "音樂與音訊",
  "CLIMATE CONTROL": "空調控制",
  "REAR ZONE TEMP": "後座溫度",
  "FAN: 3": "風量：3",
  "SYNC": "同步",
  "REAR SEAT COMM.": "後座通訊",
  "DRIVER CALL": "聯絡駕駛",
  "IDLE": "待命",
  "CALL": "呼叫",
  "JOURNEY REQUEST": "行程提案",
  "DRIVER APPROVAL REQUIRED": "需要駕駛同意",
  "ADD TO JOURNEY": "加入行程",
  "Live Journey Intelligence": "即時旅程資訊",
  "Temporarily unavailable": "暫時無法使用",
  "SYSTEM SETTINGS": "系統設定",
  "DISPLAY &amp; AUDIO": "顯示與音訊",
  "CONFIGURATION": "設定",
  "RESUME": "恢復資訊",
  "QUIET MODE": "靜謐模式",
  "REST STOP": "休息站",
  "TIME": "時間",
  "WEATHER": "天氣",
  "EXAMPLE": "示例",
  "ROUTE EXAMPLE": "路線示例",
  "Journey request sent": "行程提案已送出",
  "Route kept": "維持原路線",
  "NORMAL DRIVE · Donghu available": "正常行駛 · 東湖景點可探索",
  "Driver Load HIGH · confirmed before request": "駕駛負荷高 · 已確認，再提出行程",
  "ADD TO JOURNEY · PACT DEFER": "加入行程 · PACT 延後",
  "Driver Load NORMAL · PACT ASK": "駕駛負荷正常 · PACT 請求同意",
  "DRIVER ACCEPT · Journey updated": "駕駛接受 · 行程已更新",
  "CLOUD OFFLINE · Local Core active": "雲端離線 · 本地核心運作中",
  "QUIET MODE · Journey preserved": "靜謐模式 · 行程保留",
  "CLOUD RESTORED · Quiet remains · HELD": "雲端恢復 · 靜謐持續 · 資訊暫存",
  "RESUME · Journey Intelligence returns": "主動恢復 · 旅程資訊重新呈現",
  "Developer Scenario Director": "開發者情境控制",
  "SIMULATED vehicle, POI, ETA and cloud data · existing production HMI above": "車況、景點、抵達時間與雲端資料皆為模擬",
  "RESET": "重設",
  "LOAD HIGH": "駕駛負荷高",
  "LOAD NORMAL": "駕駛負荷正常",
  "DRIVER ACCEPT": "駕駛接受",
  "CLOUD OFFLINE": "雲端離線",
  "CLOUD RESTORE": "雲端恢復",
  "AUTO PLAY": "自動播放",
  "STOP": "停止",
  "Journey request source": "行程提案來源",
  "Rear": "後座",
  "Window": "智慧車窗",
  "Film Mode · longer recording holds": "影片模式 · 延長各階段停留",
  "FILM · timed, simulated ACCEPT / RESUME": "影片模式 · 定時模擬接受與恢復",
  "MANUAL · human ACCEPT / RESUME": "手動模式 · 人工接受與恢復",
  "END · RESUME confirmed": "結束 · 已確認恢復",
  "WAITING · Human DRIVER ACCEPT required": "等待駕駛主動接受",
  "HELD · Human RESUME required": "資訊暫存 · 等待主動恢復",
  "Ready": "就緒",
  "Starting": "啟動中",
  "Stopped · current scenario state preserved": "已停止 · 保留目前情境",
  "Playback failed": "播放失敗",
  "Playback evidence ·": "播放證據 ·",
  "Local Core active · permission / policy / attention / journey / rear experience": "本地核心運作中 · 權限／策略／注意力／行程／後座體驗",
  "Developer Scenario Inspector (test harness)": "開發者情境檢查器（測試工具）",
  "DRIVE · FOCUS": "行駛 · 專注",
  "DRIVE": "行駛",
  "Power": "動力",
  "Trip:": "里程：",
  "Avg:": "平均：",
  "Time:": "時間：",
  "Range:": "續航：",
  "TIRE PRESSURE": "胎壓",
  "Temp: 19°C": "溫度：19°C",
  "Next ·": "下一站 ·",
  "CRITICAL SAFETY WARNING": "重大安全警示",
  "Immediate safety condition detected": "偵測到需立即處理的安全狀況",
  "Driver display": "駕駛資訊",
  "Cluster": "儀表",
  "Journey & control": "行程與控制",
  "Center": "中控",
  "Passenger discovery": "副駕探索",
  "Front passenger": "前座副駕",
  "Passenger": "副駕",
  "Rear comfort": "後座舒適體驗",
  "Rear passenger": "後座乘員",
  "Ambient context": "環境資訊",
  "Interactive window": "互動車窗",
  "Premium Journey · existing five-display HMI": "高階旅程 · 五屏座艙",
  "Multi-display simulator": "多屏模擬器",
  "Illustrative simulation": "模擬示例",
  "Stop listening": "停止聆聽",
  "Try voice again": "重試語音",
  "Listen": "聆聽",
  "You:": "你：",
  "Invalid display entry. No Gateway connection opened.": "無效的螢幕入口，尚未建立閘道連線。",
  "Developer tools · outside all five display previews": "開發工具 · 獨立於五屏之外",
  "HMI Gateway Control Console": "HMI 閘道控制台",
  "Vehicle speed": "車速",
  "Send vehicle.telemetry.report": "送出模擬車速",
  "Simulated driver cognitive load": "模擬駕駛認知負荷",
  "Report low load": "低負荷",
  "Report normal load": "正常負荷",
  "Report high load": "高負荷",
  "Report critical load": "極高負荷",
  "Simulated network condition": "模擬連線狀態",
  "Set network online": "設為連線",
  "Set network degraded": "設為連線受限",
  "Set network offline": "設為離線",
  "Connection:": "連線：",
  "Last gateway message:": "最新閘道訊息：",
  "No substantiated recommendation": "沒有足夠依據提供建議",
  "Recommendation request failed": "建議請求失敗",
  "Sent to Action Gate · waiting for Center consent": "已送交策略閘道，等待中控確認",
  "Simulated evidence": "模擬依據",
  "Evidence-backed recommendation": "有依據的建議",
  "Evidence": "依據",
  "Provenance unavailable": "來源資訊不可用",
  "Rationale and evidence details": "建議理由與依據",
  "Recommendation factors": "建議因素",
  "No factor provenance was returned.": "尚未取得因素來源。",
  "Whole journey context": "完整旅程資訊",
  "No whole-journey provenance was returned.": "尚未取得完整旅程來源。",
  "Other options considered": "其他候選項目",
  "Send to driver approval": "送交駕駛確認",
  "Reviewed by driver · journey unchanged": "駕駛已閱 · 行程未變",
  "Driver approved · journey unchanged": "駕駛同意 · 行程未變",
  "Deferred · waiting for driver load to fall": "已延後 · 等待駕駛負荷降低",
  "Released · driver load is clear, approval required": "負荷已降低 · 等待駕駛同意",
  "Awaiting driver approval": "等待駕駛同意",
  "Added to journey": "已加入行程",
  "Simulator guidance shown · no vehicle control": "模擬引導已顯示 · 不控制車輛",
  "Simulator guidance enabled · no vehicle control": "模擬引導已啟用 · 不控制車輛",
  "Declined by driver · journey unchanged": "駕駛已拒絕 · 行程未變",
  "Interrupted · safety event took priority": "已中止 · 安全事件優先",
  "Task · simulator only": "任務 · 僅供模擬",
  "Goal": "目標",
  "Current step": "目前步驟",
  "Next known step": "下一個已知步驟",
  "Condition key": "條件識別碼",
  "Evidence class": "依據類別",
  "Unknown": "未知",
  "Confirmed by user": "使用者已確認",
  "Inferred (explicit evidence)": "推斷（明確依據）",
  "Condition value": "條件值",
  "Leave blank when unknown": "未知時請留白",
  "Condition source: simulated input. Editing one condition preserves the others and advances the task version.": "來源為模擬輸入；修改單一條件會保留其他條件並更新任務版本。",
  "Update task": "更新任務",
  "Record simulator outcome": "記錄模擬結果",
  "Action label": "動作名稱",
  "Action result": "動作結果",
  "Succeeded": "成功",
  "Failed": "失敗",
  "Ledger record only. No vehicle action is sent or retried.": "僅記錄結果，不送出或重試車輛動作。",
  "Cancel task": "取消任務",
  "Request resume": "請求恢復",
  "Resume is unavailable without fresh candidate, capability, authorization, and outcome revalidation. Requests fail closed here.": "候選、能力、授權與結果未重新驗證前，不允許恢復。",
  "Start a task": "建立任務",
  "Simulator task state and ledger. No live vehicle capability or control is connected.": "模擬任務與操作紀錄；尚未接入實車能力或控制。",
  "Task": "任務",
  "Version / status": "版本／狀態",
  "Pause / reason": "暫停／原因",
  "Conditions · class / source": "條件 · 類別／來源",
  "Action ledger": "動作紀錄",
  "No conditions recorded.": "尚無條件紀錄。",
  "No action outcomes recorded.": "尚無動作結果。",
  "New task goal": "新任務目標",
  "Start simulator task": "建立模擬任務",
  "Assistance Timing Preview (Simulator Only)": "介入時機預覽（僅供模擬）",
  "This panel computes the timing policy locally without routing content or sending protocol commands.": "此工具僅在本機計算介入時機，不傳送內容或協定指令。",
  "Simulated Information Value:": "模擬資訊價值：",
  "Negligible": "可忽略",
  "Useful": "有幫助",
  "Important": "重要",
  "Simulated Urgency:": "模擬緊急程度：",
  "Low": "低",
  "Normal": "正常",
  "High": "高",
  "Critical": "極高",
  "Simulated Interruption Cost:": "模擬打擾成本：",
  "Moderate": "中",
  "Simulated Driver Load:": "模擬駕駛負荷：",
  "Simulated Sensitivity:": "模擬敏感程度：",
  "Ordinary": "一般",
  "Sensitive": "敏感",
  "Simulated Passenger Handoff Authorized": "模擬乘員接手已授權",
  "Simulator-only Result": "模擬結果",
  "Outcome:": "結果：",
  "Reason Code:": "原因碼：",
  "[Simulated Content Preview Rendered]": "［模擬內容預覽］",
  "Developer Scenario Inspector": "開發者情境檢查器",
  "Premium Journey · Test Harness Only": "高階旅程 · 僅供測試",
  "Open existing AURA production HMI": "開啟 AURA 正式五屏",
  "Interactive Prototype · SIMULATED VEHICLE CONTEXT · SIMULATED CLOUD SERVICES": "互動原型 · 模擬車況 · 模擬雲端服務",
  "Five displays": "五屏",
  "Demo Director / PACT X-Ray": "情境控制／PACT 決策觀測",
  "Shared Journey": "共享行程",
  "Your journey": "你的旅程",
  "Premium Executive Travel": "高階商務旅程",
  "Shared journey context": "共享旅程資訊",
  "Scenic lakeside stop": "湖畔景點停留",
  "NEXT STOP": "下一站",
  "Driver Operations": "駕駛資訊",
  "FOCUS MODE": "專注模式",
  "Continue on current route": "沿目前路線繼續行駛",
  "Journey updated · Donghu added": "行程已更新 · 已加入東湖",
  "Request held · driver interruption suppressed": "提案延後 · 暫不打擾駕駛",
  "Donghu is part of the shared journey": "東湖已加入共享行程",
  "Current route preserved": "保留目前路線",
  "Your private journey": "你的專屬旅程",
  "Arrival 14:26 · Route Status Optimal": "抵達 14:26 · 路線順暢",
  "Journey continues": "旅程持續",
  "Route kept · request declined": "維持路線 · 提案已拒絕",
  "Scenic Experience": "景點探索",
  "· Gateway": "· 閘道",
  "Gateway": "閘道",
  "Action Gate rejected this proposal (": "策略閘道拒絕提案（",
  "). The journey was not changed; review the recommendation or request another one.": "）。行程未變，請檢視建議或重新詢問。",
  ". The journey changes only after the driver approves through Center consent.": "。駕駛在中控確認後才更新行程。",
  "signal · active since": "訊號 · 啟用時間",
  "Does proximity to an entrance or passenger drop-off space matter?": "是否需要靠近入口或方便乘員下車？",
  "Yes, it matters": "需要",
  "No, no special preference": "沒有特別偏好",
  "Source: simulator · Freshness:": "來源：模擬 · 時效：",
  "· no vehicle control": "· 不控制車輛",
  "Route: API ·": "路線：API ·",
  "· Freshness:": "· 時效：",
  "· observed": "· 觀測時間",
  "Place: API ·": "地點：API ·",
  "· consent reviews only; journey unchanged": "· 僅確認資訊，行程未變",
  "Passenger route preview · API · temporary use": "乘員路線預覽 · API · 暫時使用",
  "Route freshness:": "路線時效：",
  "Place freshness:": "地點時效：",
  "SIMULATED parking assistance": "模擬停車輔助",
  "Source: simulator · no vehicle control": "來源：模擬 · 不控制車輛",
  "Center gateway": "中控閘道",
  "0:00 / 3:00 • SIMULATED • NO AUDIO": "0:00 / 3:00 • 模擬 • 無音訊",
  "· SIMULATED": "· 模擬",
  "12°C · RAIN": "12°C · 雨",
  "ALPINE ROAD ·": "高山道路 ·",
  "· NEXT STOP": "· 下一站",
  "min to journey": "分鐘繞路時間",
  "Protocol v1 · center-main / main-computer · shared vehicle speed": "協定 v1 · center-main / main-computer · 共享車速",
  "· driver load": "· 駕駛負荷",
  "· connectivity": "· 連線",
  "Five logical registry sockets share this one browser simulation; this does not demonstrate five physical displays or independent hardware clients.": "此瀏覽器模擬五個邏輯螢幕，並非五個實體螢幕或獨立硬體。",
  "Cluster motion": "儀表車道動畫",
  "Scenario&nbsp;": "情境&nbsp;",
  "Munich → Stuttgart": "慕尼黑 → 斯圖加特",
  "Illustrative route values · shared vehicle telemetry updates when the gateway is connected": "路線數據為模擬；閘道連線後同步共享車況",
  "Immediate safety condition ·": "需立即處理的安全狀況 ·",
  "· existing Gateway commands": "· 沿用閘道指令",
  "observed steps": "個已觀測步驟",
  "· cloud": "· 雲端",
  "Safety warning ·": "安全警示 ·",
  "Donghu · +12 min": "東湖 · +12 分鐘",
  "DEMO DATA ·": "模擬資料 ·",
  "DONGHU": "東湖",
  "+12 min to journey": "行程增加 12 分鐘",
  "Local: permission, policy, attention, journey state, rear experience. Cloud data is a deterministic fixture; no external live traffic service is connected.": "本地提供權限、策略、注意力、行程與後座體驗；雲端資料為固定模擬，未接入即時交通服務。",
  "Task command": "任務指令",
  "No journey recommendation source is configured on this host. No provider data was queried and no recommendation was generated.": "此主機尚未設定旅程建議來源，未查詢外部資料或產生建議。",
  "The journey evidence source failed. No recommendation was generated.": "旅程資料來源失敗，未產生建議。",
  "The journey evidence source returned no trip data. No recommendation was generated.": "來源未提供旅程資料，未產生建議。",
  "Fresh origin, destination, and current-route evidence is required. The available trip context was incomplete or stale.": "需要最新起點、目的地與路線資訊；目前資料不完整或已過期。",
  "No fresh decision evidence was available. No recommendation was generated.": "沒有最新決策依據，未產生建議。",
  "A fresh route detour could not be verified. No recommendation was generated.": "無法確認最新繞路資訊，未產生建議。",
  "The available evidence did not substantiate a journey recommendation.": "現有依據不足以提供旅程建議。",
  "SIMULATED parking context · driver choice": "模擬停車資訊 · 駕駛決定",
  "Passenger route preview · provider data · driver choice": "乘員路線預覽 · 來源資料 · 駕駛決定",
  "Shuffle": "隨機播放",
  "Previous track": "上一首",
  "Play": "播放",
  "Next track": "下一首",
  "Repeat": "重複播放",
  "Volume": "音量",
  "Lower temperature": "降低溫度",
  "Raise temperature": "提高溫度",
  "Find a place where Mom can get out, with charging nearby": "找一個方便媽媽下車、附近可以充電的地點",
  "Donghu": "東湖",
  "connected": "已連線",
  "connecting": "連線中",
  "disconnected": "已斷線",
  "error": "錯誤",
  "normal": "正常",
  "high": "高",
  "low": "低",
  "critical": "極高",
  "quiet": "靜謐",
  "online": "連線",
  "offline": "離線",
  "degraded": "連線受限",
  "presented": "顯示中",
  "available_but_held": "可用，暫存",
  "unavailable": "無法使用",
  "RUNNING": "播放中",
  "COMPLETE": "完成",
  "STOPPED": "已停止",
  "ERROR": "錯誤",
  "PENDING": "等待中",
  "OFFLINE": "離線",
  "DEFER": "延後（DEFER）",
  "ASK": "請求同意（ASK）",
  "EXECUTE": "執行（EXECUTE）",
  "ROUTE": "導向（ROUTE）",
  "rear": "後座",
  "interactive_window": "智慧車窗",
  "center": "中控",
  "cluster": "儀表",
  "front_passenger": "副駕",
  "simulated": "模擬",
  "fresh": "最新",
  "unknown": "未知",
  "cached": "快取",
  "stale": "過期",
  "active": "運作中",
  "succeeded": "成功",
  "failed": "失敗",
  "confirmed": "已確認",
  "inferred": "已推斷",
  "completed": "已完成",
  "cancelled": "已取消",
  "running": "執行中",
  "interrupted": "已中止",
  "awaiting_consent": "等待同意",
  "deferred": "已延後",
  "declined": "已拒絕",
  "executing": "執行中",
  "The Midnight Echo": "午夜回聲",
  "AQUAMARINE": "海藍餐廳",
  "THE FLAME": "焰火",
  "AURORA": "曙光",
  "TERRA": "大地",
  "OCCUPANT": "乘員",
  "INTENT": "意圖",
  "RESOURCE": "資源",
  "AUTHORITY": "決定權",
  "DRIVER LOAD": "駕駛負荷",
  "CONNECTIVITY": "連線",
  "DECISION": "決策",
  "SOURCE DISPLAY": "來源畫面",
  "TARGET": "目標",
  "REASON CODE": "原因碼",
  "TRACE ID": "追蹤 ID",
  "REAR ZONE": "後座模式",
  "PRESENTATION": "資訊呈現",
  "REAR VIP": "後座 VIP（模擬）",
  "REAR VIP ZONE": "後座個人區域",
  "SHARED JOURNEY": "共享行程",
  "DRIVER": "駕駛",
  "ADD JOURNEY STOP": "加入停靠點",
  "REAR + WINDOW": "後座與智慧車窗",
  "all": "全部",
  "window": "智慧車窗",
  "passenger": "副駕",
  "Registered": "已註冊",
  "Shared state snapshot received": "已收到共享狀態",
  "Connecting to gateway": "連線至閘道中",
  "Gateway unavailable": "閘道不可用",
  "Rear cabin": "後座座艙",
  "Rear display": "後座畫面",
  "Smart Window": "智慧車窗",
  "Rear VIP": "後座 VIP",
  "Unspecified": "未指定",
  "Not set": "尚未設定",
  "None": "無",
  "Playback stopped": "播放已停止",
  "Gateway disconnected; playback stopped": "閘道斷線，播放已停止",
  "Journey changed before driver consent; playback stopped": "同意前行程被改動，播放已停止",
  "Driver Load HIGH required before journey request; playback stopped": "提案前必須確認高負荷，播放已停止",
  "Command not sent": "指令未送出",
  "Timed out waiting for shared state": "等待共享狀態逾時"
};
export function uiText(value: unknown): string {
 const text = value == null ? "—" : String(value);
 if (Object.hasOwn(copy, text)) return copy[text]!;
 if (/^[\w:./-]+$/.test(text)) return text;
 const separator = text.indexOf(": ");
 if (separator > 0 && Object.hasOwn(copy, text.slice(0, separator))) return copy[text.slice(0, separator)] + "：" + uiText(text.slice(separator + 2));
 return text.replace(/\bDonghu\b/gi, "東湖").replace(/(\d+) min\b/g, "$1 分鐘");
}
